name: CI

on:
  push:
    # Trigger 1: When main branch is updated (respects path ignores)
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

    # Trigger 2: When a version tag is pushed
    tags:
      - 'v*'

  # checkov:skip=CKV_GHA_7: Inputs are required for manual targeting
  workflow_dispatch:
    inputs:
      fail-on-no-release:
        description: 'Fail the workflow if no release is published (e.g. if there are no relevant commits).'
        type: boolean
        default: true
      publish:
        description: 'Whether to run in publish mode.'
        type: boolean

concurrency:
  group: '${{ github.repository_id }}-${{ github.ref_name }}'
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  meta:
    name: Meta
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      is-first-commit: ${{ steps.check-if-first-commit.outputs.is-first-commit == 'true' }}
      repo-owner: ${{ steps.repo-info.outputs.repo-owner }}
      repo-name: ${{ steps.repo-info.outputs.repo-name }}

    steps:
      - name: Check if this is the first commit
        id: check-if-first-commit
        uses: stairwaytowonderland/actions/.github/actions/first-commit-action@v1
      - name: Get repo info
        id: repo-info
        uses: stairwaytowonderland/actions/.github/actions/repo-info-action@v1

  release:
    name: Release
    if: startsWith(github.ref, 'refs/heads/main') && ! inputs.publish
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      # dispatch-workflow: publish.yml
      fail-on-no-release: ${{ inputs.fail-on-no-release == true }}

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/v') || inputs.publish
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}

  update-majorver:
    name: Update Major Version Tag
    needs: [publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: nowactions/update-majorver@v1
