name: Import Issues from CSV

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  repository_dispatch:
    types: [create-issues]

  # checkov:skip=CKV_GHA_7: Inputs are required for manual targeting
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true

      csv-path:
        description: 'Path (relative) to the CSV file'
        type: string
        default: 'TODO.csv'

permissions:
  contents: read
  issues: write

jobs:
  import-issues:
    name: Import Issues
    uses: stairwaytowonderland/issue-management/.github/workflows/import-csv-issues.yaml@v1
    secrets: inherit
    with:
      batch: true
      csv-path: ${{ inputs.csv-path || 'TODO.csv' }}
      dry-run: ${{ inputs.dry-run == true }}
