name: Release a Version

on:
  workflow_call:
    inputs:
      dispatch-workflow:
        description: 'The workflow file to dispatch after a successful release.'
        type: string
      fail-on-no-release:
        description:
          'Fail the workflow if no release is published (e.g. if there are no
          relevant commits).'
        type: boolean
      ref:
        description:
          'The git ref or sha to release (e.g. refs/heads/main). Defaults to the
          current ref.'
        type: string

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: stairwaytowonderland/actions/.github/workflows/release.yaml@v1
    secrets: inherit
    with:
      dispatch-workflow: ${{ inputs.dispatch-workflow }}
      fail-on-no-release: ${{ inputs.fail-on-no-release }}
      ref: ${{ inputs.ref || github.ref }}
