name: 🌟 Stargazers

permissions:
  contents: read

on:
  watch:
    types: [started]

jobs:
  stargazers:
    name: 🌟 On Star
    uses: stairwaytowonderland/.github/.github/workflows/stargazers.yaml@v1
    secrets: inherit
