name: CI Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read # access to read repository's content
  actions: read # access to reading actions

jobs:
  basic-validation:
    name: Basic Validation
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main
    with:
      operating-systems: '["ubuntu-latest"]'
      enable-audit: false

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v7

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
